### ISSUE TITLE
Add d3.movingAverage as a native d3-array function

### ISSUE THREAD

**Issue by rdmurphy** [d3/d3-array#176] opened 2020-09-25 04:46 UTC
I've borrowed the moving average function [found in this notebook](https://observablehq.com/@d3/moving-average) a few times now, and having just done it again 😁 it made me wonder if it belongs in d3-array proper? I feel like it has a similar vibe to `d3.cumsum`.

The only pause I have is whether there is an issue with its definition of what constitutes the "moving average." I think I know how to modify to be center-based ((N - 1) / 2 values on either side of V vs. V and N - 1 previous values), but don't know if alternative definitions would/should be on the d3-array namespace under different names or as options to pass to a `d3.movingAverage` itself.

Either way, thank you!

**Comment by Fil** [comment] 2020-09-25 09:49
this or d3.blur would be great yes.

Closing as a duplicate of https://github.com/d3/d3-array/issues/56 (in particular https://github.com/d3/d3-array/issues/56#issuecomment-609674095)

**Closed by Fil** 2020-09-25 09:49 UTC
