### ISSUE TITLE
d3-array

### ISSUE THREAD

**Issue by fladower** [d3/d3-array#81] opened 2018-11-10 13:05 UTC
hi,
When I used "npm run build", the console has error, it says "SyntaxError: Unexpected token: name (index) [./~/_d3-array@1.3.0@d3-array/dist/d3-array.js:168,0]"

https://github.com/d3/d3-array/blob/c95d28e5a0f6799d20b3612e07a097103ea16631/src/rollup.js#L3

**Comment by mbostock** [comment] 2018-11-10 14:42
Duplicate of #80.

**Closed by mbostock** 2018-11-10 14:42 UTC
